version: "3.9"
services: 
    redis:
        image: 639962416620.dkr.ecr.eu-west-1.amazonaws.com/redis:5.0-alpine3.10
        networks: 
            - redis-network
        # volumes:
        #     - "./redis-check:/redis-check"
        healthcheck:
            test: /redis-check/script.sh
            interval: "5s"
    
    db:
        image: 639962416620.dkr.ecr.eu-west-1.amazonaws.com/postgres:9.4
        # volumes: 
        #     - "data-postgres:/var/lib/postgresql/data"
        #     - "./postgres-check:/postgrescheck"
        environment: 
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
        networks: 
            - postgres-network
        healthcheck:
            test: /postgrescheck/script.sh
            interval: "5s"

    vote:
        image: 639962416620.dkr.ecr.eu-west-1.amazonaws.com/vote
        ports:  
            - "8080:80"
        depends_on: 
            - redis
        networks: 
            - redis-network

    result:
        image: 639962416620.dkr.ecr.eu-west-1.amazonaws.com/result
        ports:
            - "4000:4000"
        depends_on: 
            - db
        networks: 
            - postgres-network

    worker:
        image: 639962416620.dkr.ecr.eu-west-1.amazonaws.com/worker
        depends_on: 
            redis:
                condition: service_healthy
            db:
                condition: service_healthy    
        networks: 
            - postgres-network
            - redis-network

# volumes: 
#     data-postgres:

networks: 
    postgres-network:
    redis-network:

